context:
  - label:
      eng: 1 sentence
      swe: 1 mening
    value: 1 sentence
description:
  swe: <b>Grundades 1891 av Julius Sundblom. Utkommer på Åland.</b><br><br><p>Korpusen
    är del av språkbanken för finlandssvenska inom projektet <i>Svenskan i Finland
    – i dag och i går</i>. Läs mer hos <a href="https://www.sls.fi/sv/infrastruktur-oversiktsprojekt#svenskan-i-finland-i-dag-och-i-gr-20102017">Svenska
    litteratursällskapet i Finland</a></p>
  eng: Part of the Finland Swedish language bank over Swedish in Finland today and
    yesterday
id: testcorpus
mode:
  - name: default


pos_attributes:
  - pos: pos

title:
  swe: 'Under Ivask'
  eng: 'Under and Ivask correspondence'
within:
  - label:
      eng: sentence
      swe: mening
    value: sentence
