context:
  - label:
      eng: 1 paragraph
      swe: 1 paragraph
    value: 1 paragraph
description:
  swe: Under Ivask
  eng: Under and Ivask short
id: underivask
mode:
  - name: litterary


pos_attributes:
  - baseform: lemma
  - pos: epos
  - number: number

title:
  swe: 'Under-Ivask'
  eng: 'Under-Ivask'
within:
  - label:
      eng: sentence
      swe: mening
    value: sentence
