context:
  - label:
      eng: 1 sentence
      swe: 1 mening
    value: 1 sentence
description:
  swe: Under Ivask
  eng: Under and Ivask short
id: underivask
mode:
  - name: default


pos_attributes:
  - pos: pos

title:
  swe: 'Under-Ivask'
  eng: 'Under-Ivask'
within:
  - label:
      eng: sentence
      swe: mening
    value: sentence
